---
title: "Embedded-Systems"
---

## Calendar 2025 Winter

- In-Class Assessments (ICA's); 10 total; 30% of final mark; 3% each.
- All In-Class Assessments (ICA's) are due on Sunday of the week at 11:59 PM.
- Labs; 5 total; 10% of final mark; 2% each.
- All Labs are due on Sunday of the week at 11:59 PM.
- Practical Assessments (PA's); 3 total; 60% of final mark; 20% each.
- All Practical Assessments (PA's) are done during class time.
- All Assessments are to be uploaded (pushed) to your github workbook repo.

|Week|Assessment|Day1 (2 hrs)|Day2 (2 hrs)|
|:-:|:-:|:-:|:-:|
|1-J06||Intro<br> Github-Repo<br> Toolchain-Setup|Intro<br> Github-Repo<br> Toolchain-Setup|
|2-J13|ICA01-Prog-Workflow|Demo1<br> Workflow<br> Data-Types<br> Bitwise-Ops|Demo1<br> Workflow<br> Data-Types<br> Bitwise-Ops|
|3-J20|ICA02-Code-Migrate|Debugging<br> Breakpoints|Debugging<br> Breakpoints|
|4-J27|ICA03-Bitwise-Ops|GPIO-LED-Switches|GPIO-LED-Switches|
|5-F03|ICA04-AD2-Measure|Measure Freq with AD2<br> Switch States|Measure Freq with AD2<br> Switch Debouncing|
|6-F10|ICA05-SWL-Lib|SWL-Library|Practical Assessment 1|
|F17||READING-WEEK|READING-WEEK|
|7-F24|ICA06-PLL|Phased-Locked-Loop|PLL|
|8-M03|ICA07-RTI|Real-Time-Interrupt|RTI|
|9-M10|ICA08-SCI-Basic<br> Lab01-SCI|Serial-Com-Interface|SCI|
|10-M17|ICA09-Segs-Basic|7-Segment-Display|7-Segs-Display|
|11-M24|Lab02-16-bit-Segs|16-bit-Segs|16-bit-Segs|
|12-M31|Lab03-Dec-Entry|Decimal-Entry-Conversion|Practical Assessment 2|
|13-A07|ICA12-LCD|Liquid-Crystal-Display|LCD|
|14-A14|Lab04-Sec-LCD-Functions|Character-Buffers<br> sprint|Character-Buffers<br> sprint|
|15-A21|Lab05-Dynamic-LCD|Dynamic-LCD|Practical Assessment 3|

## General Resources

- [CMPE1250 Winter of 2022 Lectures by Carlos Estay](https://www.youtube.com/playlist?list=PLtPfFKnaEIMhBkhTIAGLfNPb6v0TRwFqm){target="_blank"}
  - youtube video playlist; 29 videos.

- [CMPE1250 Winter of 2023 Lectures by Carlos Estay](https://www.youtube.com/playlist?list=PLtPfFKnaEIMj5lHarN9wmaAMJDxcYGMpB){target="_blank"}
  - youtube video playlist; 4 videos.

- [CMPE1250 Fall of 2023 Lectures by Carlos Estay](https://www.youtube.com/playlist?list=PLtPfFKnaEIMjgGVukyIIZQNxSEmmFh_K8){target="_blank"}
  - youtube video playlist; 38 videos.


- [CMPE1250 Fall of 2024 Lectures by Carlos Estay](https://www.youtube.com/playlist?list=PLtPfFKnaEIMipKCt70AbjncvuqiSdQ3yI){target="_blank"}
  - youtube video playlist; 40 videos.


- [CMPE2250 Winter of 2024 Lectures by Carlos Estay](https://www.youtube.com/playlist?list=PLtPfFKnaEIMic1uFGB-Vfh3B7FwUz0FHM){target="_blank"}
  - youtube video playlist; 37 videos.
