title: Robbin Law GitHub Pages
subtitle: A resource for students
author: Robbin Law
email: robbinl@nait.ca
minima:
  date_format: "%b %-d, %Y"
github_username: robbinl
description: A collection of notes and resources.
show_excerpts: false # set to true to show excerpts on the homepage

header_pages:
 - comp1017/index.md
 - dmit1530/index.md
 - cpsc1520/index.md
 - anap1525/index.md
 #- cpsc1012/index.md
 #- cpsc1517/index.md
 #- dmit2018/index.md
 #- about.md

exclude:
  README.md
theme: minima

favicon: favicon.ico