title: Robbin Law
#subtitle: A resource for students
#author: Robbin Law
email: robbinlaw@gmail.com
minima:
  date_format: "%b %-d, %Y"
github_username: robbinl
description: A collection of notes and resources.
show_excerpts: false # set to true to show excerpts on the homepage

header_pages:
 - cpsc1012/index.md
 - dmit1508/index.md
 - comp1017/index.md
 - dmit1530/index.md
 - cpsc1520/index.md
 - cpsc1517/index.md
 - anap1525/index.md
 - dmit2008/index.md
 - dmit2018/index.md
 #- about.md

# exclude:
#   README.md

theme: minima

favicon: favicon.ico