---
title: "Semiconductors"
---

## Calendar 2025 Winter

- Projects (P); 8 total; 64% of final mark; 8% each.
- All Projects are due on Sunday of the week at 11:59 PM.
- Labs (L); 9 total; 18% of final mark; 2% each.
- All Labs are due on Sunday of the week at 11:59 PM.
- Exams (E); 3 total; 18% of final mark; 6% each.
- All Exams are done during class time.

|Week|Assessment|Day1 (2 hrs)|Day2 (2 hrs)|Day3 (1 hr)|
|:-:|:-:|:-:|:-:|:-:|
|1-J06|L1-Diodes||Intro/Diode-Physics|Diode-Models|
|2-J13|L2-Rectifiers|Rectifiers|Rectifiers|Rectifiers|
|3-J20|L3-Filtering/Reg|Filtering/Regulation|Filtering/Regulation|Filtering/Regulation|
|4-J27|P1-Power-Supply|BJT-Intro|BJT-Switching|BJT-Biasing|
|5-F03|L4-BJT-Switch/Bias<br> |BJT-Totem-Pole|BJT-H-Bridge|BJT-H-Bridge|
|6-F10|P2-TPole/HBridge<br> L5-FET-Switching|FET-Intro|FET-Switching|Exam1-Diode-Apps|
|F17||READING-WEEK|READING-WEEK|READING-WEEK|
|7-F24|P3-Transistors<br> L6-OpAmps|OpAmps-Intro|OpAmps-Configs|OpAmps-Diff-Amps|
|8-M03|P4-Summing-Amps|Summing-Amps|Summing-Amps|Exam2-Transistor-Apps|
|9-M10|P5-Instrument-Amps|Instrument-Amps|Instrument-Amps|Instrument-Amps|
|10-M17|L7-DAC<br> P7-Adv-Filters/DAC<br> DAC part only|Dig-Analog-Con|Dig-Analog-Con|Dig-Analog-Con|
|11-M24|P6-Issues/Basic-Filters|OpAmp-Issues|Basic-Filters|Basic-Filters|
|12-M31|P7-Adv-Filters/DAC<br> Adv-Filters part only|Adv-Filters|Adv-Filters|Adv-Filters|
|13-A07|L8-Comparators|Comparators|Comparators|Exam3-OpAmp-Apps|
|14-A14|L9-ADC|ADC|ADC|EASTER|
|15-A21|P8-Comparators-ADC|EASTER|P8|P8|

## General Resources

- [CMPE1400 Lessons, Projects, Labs, and SA's with NO ANSWERS by Ross Taylor](assets/CMPE1400PDFs.pdf){target="_blank"}

- [CMPE1400 Formula Sheet](assets/CMPE1400-Formula-Sheet.pdf){target="_blank"}

- [Semiconductors by Circuit Bread](https://www.youtube.com/watch?v=n2S7kN12RDQ&list=PLfYdTiQCV_p7sDswtLZKK43BWOd2mTmHC){target="_blank"}
  - youtube video playlist; first 12 are on diodes, next 9 are on transistors.

- [Transistors, How do they work by Lesics](https://www.youtube.com/watch?v=7ukDKVHnac4){target="_blank"}
  - youtube video 6.52 min

- [Why it was almost impossible to make the blue LED by Veritasum](https://www.youtube.com/watch?v=AF8d72mA41M){target="_blank"}
  - youtube video 33.44 min; very good history lesson with great animations.