---
title: "Join Github Classroom"
---

## Step 1 Create a GitHub Account

- [GitHub Website](https://github.com){target="_blank"}
- Go to GitHub and create an account. Choose an appropriate username that has your first and last name in it. Remember the username that you create the account with as well as the email that you use. You will need this information to complete the setup.

## Step 2 Join Github Classroom and Create Your Workbook Repo

- Click the link below for your class and follow the instructions. Look for your name and click on it to begin the process.
- [Link to Github Classroom for CMPE1250-A02](https://classroom.github.com/a/a-ya42nn){target="_blank"}
- [Link to Github Classroom for CMPE1250-A03](https://classroom.github.com/a/lH3VDvQI){target="_blank"}

## Step 3 Accept Invitation to Join a Github Team

- An invitation should have been sent to you via an email. Accept the invitation, which will allow you read access to a `InClassDemos` submodule.

## Step 4 Clone your Github Workbook Repo to a local machine

- Sign into Github and click on your profile pic (top right) and then click on your organizations.
- If you missed Step 3 you can still accept the invitation here.
- Click on the organization called `CMPE1250` and you will see your workbook repo, click on it and from the `green` dropdown copy the url to the clip board.
- Open a terminal and make the working folder the place that you want to clone the github workbook repo.
- Type the following command to clone the github workbook repo to this local machine:
```github
git clone url
```

- for example
```
git clone https://github.com/RobbinLawComputerEngineering/Semiconductors-Public.git
```

- Now change directories to the root folder of the cloned repo using the `cd` command.

- From the root folder of the cloned repo run the following command to update the submodule where demos are provided:
```
./update.cmd
```
- In your workbook repo create a new folder just under the root level called `demos`.

- From the submodule `InClassDemos` copy the demo that you are interested in to the newly created `demos` folder in your workbook repo, then you can make changes to the demo and experiment, and save your work in the `demos` folder of your workbook repo. You cannot save work to the submodule as it is read only.
